# Generated by Django 4.1.1 on 2022-09-10 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='classsection',
            name='number_id',
        ),
        migrations.RemoveField(
            model_name='classsection',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='classusers',
            name='number_id',
        ),
        migrations.RemoveField(
            model_name='classusers',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='classusers',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='classusers',
            name='uid',
        ),
        migrations.DeleteModel(
            name='ClassNumber',
        ),
        migrations.DeleteModel(
            name='ClassSection',
        ),
        migrations.DeleteModel(
            name='ClassSubject',
        ),
        migrations.DeleteModel(
            name='ClassUsers',
        ),
    ]
