# Generated by Django 4.1.1 on 2022-09-11 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
